import { Archive as ArchiveIcon, CalendarDays, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { VeloraShell } from "@/components/VeloraShell";
import { Button } from "@/components/ui/button";

export default function Archive() {
  const archive = trpc.archives.list.useQuery();
  const remove = trpc.archives.delete.useMutation({ onSuccess: () => { archive.refetch(); toast.success("Archived story removed."); }, onError: error => toast.error(error.message) });
  return <VeloraShell><div className="mx-auto max-w-5xl px-4 pb-10 pt-7 sm:px-6"><p className="velora-label">Private by design</p><h1 className="mt-2 font-display text-4xl font-semibold tracking-[-.055em]">Story archive.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Expired stories leave public surfaces after 24 hours, but your past moments remain available only to your active Velora identity.</p>{archive.isLoading ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1, 2, 3].map(item => <div key={item} className="velora-surface aspect-[.8] animate-pulse" />)}</div> : archive.data?.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{archive.data.map(item => <article key={item.archive.id} className="velora-surface overflow-hidden"><div className="aspect-[.85] bg-muted">{item.media.mimeType.startsWith("video/") ? <video src={item.media.url} className="h-full w-full object-cover" controls /> : <img src={item.media.url} alt={item.media.altText || item.archive.caption || "Archived story"} className="h-full w-full object-cover" />}</div><div className="p-4"><p className="line-clamp-2 text-sm leading-6">{item.archive.caption || "Archived story"}</p><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5" />Expired {new Date(item.archive.expiredAt).toLocaleDateString()}</p><Button size="sm" variant="ghost" className="mt-3 rounded-lg text-destructive hover:bg-destructive/10 hover:text-destructive" onClick={() => remove.mutate({ archiveId: item.archive.id })} disabled={remove.isPending}><Trash2 className="mr-2 h-3.5 w-3.5" />Delete archive</Button></div></article>)}</div> : <div className="velora-empty mt-7"><ArchiveIcon className="h-7 w-7 text-primary" /><h2 className="mt-4 font-display text-2xl font-semibold">Your archive is quiet.</h2><p className="mt-2 max-w-sm text-sm leading-6 text-muted-foreground">When a story expires, it will move here automatically. Archived stories are never made public again.</p></div>}</div></VeloraShell>;
}
