import { Check, History, Search, ShieldAlert, Trash2, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function AccountManagement() {
  const [query, setQuery] = useState("");
  const [submitted, setSubmitted] = useState("");
  const users = trpc.admin.users.useQuery({ query: submitted });
  const status = trpc.admin.setAccountStatus.useMutation({
    onSuccess: () => { users.refetch(); toast.success("Account state updated."); },
    onError: error => toast.error(error.message),
  });
  return <section className="velora-surface mt-7 overflow-hidden"><div className="border-b px-5 py-5"><h2 className="font-display text-2xl font-semibold">Account management</h2><p className="mt-1 text-sm text-muted-foreground">Search identities and apply protected account-state actions.</p><form className="mt-4 flex gap-2" onSubmit={event => { event.preventDefault(); setSubmitted(query); }}><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search handle, name, or email" className="h-10 rounded-xl" /><Button type="submit" className="rounded-xl"><Search className="mr-2 h-4 w-4" />Search</Button></form></div><div className="divide-y">{users.isLoading ? <p className="p-6 text-sm text-muted-foreground">Loading identities…</p> : users.data?.length ? users.data.map(row => <div key={row.account.id} className="flex flex-wrap items-center gap-3 p-5"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-primary/10 text-sm font-bold text-primary"><UserRound className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="font-bold">{row.account.displayName} <span className="font-normal text-muted-foreground">@{row.account.username}</span></p><p className="truncate text-xs text-muted-foreground">{row.user.email || "No email supplied"} · {row.account.status}</p></div><Button size="sm" variant={row.account.status === "suspended" ? "outline" : "destructive"} className="rounded-lg" disabled={status.isPending} onClick={() => status.mutate({ accountId: row.account.id, status: row.account.status === "suspended" ? "active" : "suspended" })}>{row.account.status === "suspended" ? "Restore" : "Suspend"}</Button></div>) : <p className="p-6 text-sm text-muted-foreground">No identities match this search.</p>}</div></section>;
}

export function ContentReview() {
  const [query, setQuery] = useState("");
  const [submitted, setSubmitted] = useState("");
  const content = trpc.admin.content.useQuery({ query: submitted });
  const remove = trpc.admin.removePost.useMutation({ onSuccess: () => { content.refetch(); toast.success("Post removed from public surfaces."); }, onError: error => toast.error(error.message) });
  return <section className="velora-surface mt-7 overflow-hidden"><div className="border-b px-5 py-5"><h2 className="font-display text-2xl font-semibold">Content review</h2><p className="mt-1 text-sm text-muted-foreground">Search captions and authors, then remove content when moderation requires it.</p><form className="mt-4 flex gap-2" onSubmit={event => { event.preventDefault(); setSubmitted(query); }}><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search captions or creators" className="h-10 rounded-xl" /><Button type="submit" className="rounded-xl"><Search className="mr-2 h-4 w-4" />Search</Button></form></div><div className="divide-y">{content.isLoading ? <p className="p-6 text-sm text-muted-foreground">Loading content…</p> : content.data?.length ? content.data.map(row => <div key={row.post.id} className="flex flex-wrap items-center gap-3 p-5"><ShieldAlert className="h-5 w-5 text-primary" /><div className="min-w-0 flex-1"><p className="line-clamp-2 text-sm font-semibold">{row.post.caption || "Media-only post"}</p><p className="mt-1 text-xs text-muted-foreground">@{row.author.username} · {row.post.deletedAt ? "Removed" : "Visible"}</p></div>{!row.post.deletedAt ? <Button size="sm" variant="destructive" className="rounded-lg" disabled={remove.isPending} onClick={() => remove.mutate({ postId: row.post.id })}><Trash2 className="mr-1 h-3.5 w-3.5" />Remove</Button> : null}</div>) : <p className="p-6 text-sm text-muted-foreground">No content matches this search.</p>}</div></section>;
}

export function FeedbackQueue() {
  const feedback = trpc.feedback.adminList.useQuery({});
  const update = trpc.feedback.adminUpdate.useMutation({ onSuccess: () => { feedback.refetch(); toast.success("Feedback status updated."); }, onError: error => toast.error(error.message) });
  return <section className="velora-surface mt-7 overflow-hidden"><div className="border-b px-5 py-5"><h2 className="font-display text-2xl font-semibold">Feedback and bug reports</h2><p className="mt-1 text-sm text-muted-foreground">Real submissions from the community, with no seeded ratings or reviews.</p></div>{feedback.isLoading ? <p className="p-6 text-sm text-muted-foreground">Loading feedback…</p> : feedback.data?.length ? <div className="divide-y">{feedback.data.map(item => <div key={item.feedback.id} className="p-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-primary">{item.feedback.type}</span>{item.feedback.rating ? <span className="text-sm font-bold">{item.feedback.rating}/5</span> : null}<span className="text-xs text-muted-foreground">by {item.user.name || item.user.email || "user"}</span></div><p className="mt-3 font-bold">{item.feedback.subject}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{item.feedback.body}</p><div className="mt-4 flex flex-wrap items-center gap-2"><span className="text-xs text-muted-foreground">Status: {item.feedback.status}</span>{item.feedback.status === "open" ? <Button size="sm" variant="outline" className="rounded-lg" onClick={() => update.mutate({ id: item.feedback.id, status: "reviewing" })}>Start review</Button> : null}{item.feedback.status === "reviewing" ? <Button size="sm" className="rounded-lg" onClick={() => update.mutate({ id: item.feedback.id, status: "resolved" })}><Check className="mr-1 h-3.5 w-3.5" />Resolve</Button> : null}</div></div>)}</div> : <p className="p-8 text-center text-sm text-muted-foreground">No real feedback or bug reports have been submitted.</p>}</section>;
}

export function VerificationQueue() {
  const pending = trpc.verification.pending.useQuery();
  const review = trpc.verification.adminReview.useMutation({ onSuccess: () => { pending.refetch(); toast.success("Verification review recorded."); }, onError: error => toast.error(error.message) });
  return <section className="velora-surface mt-7 overflow-hidden"><div className="border-b px-5 py-5"><h2 className="font-display text-2xl font-semibold">Verification review</h2><p className="mt-1 text-sm text-muted-foreground">Badges are review outcomes, not automatic rewards for popularity or ratings.</p></div>{pending.isLoading ? <p className="p-6 text-sm text-muted-foreground">Loading verification requests…</p> : pending.data?.length ? <div className="divide-y">{pending.data.map(item => <div key={item.account.id} className="flex flex-wrap items-center gap-3 p-5"><div className="min-w-0 flex-1"><p className="font-bold">{item.account.displayName} <span className="font-normal text-muted-foreground">@{item.account.username}</span></p><p className="mt-1 text-sm text-muted-foreground">{item.profile.bio || "No profile statement provided."}</p></div><div className="flex gap-2"><Button size="sm" className="rounded-lg" onClick={() => review.mutate({ accountId: item.account.id, decision: "approved" })}>Approve</Button><Button size="sm" variant="outline" className="rounded-lg" onClick={() => review.mutate({ accountId: item.account.id, decision: "rejected" })}>Reject</Button></div></div>)}</div> : <p className="p-8 text-center text-sm text-muted-foreground">No pending verification requests.</p>}</section>;
}

export function ModerationHistory() {
  const activity = trpc.admin.activity.useQuery();
  return <section className="velora-surface mt-7 overflow-hidden"><div className="flex items-center gap-3 border-b px-5 py-5"><History className="h-5 w-5 text-primary" /><div><h2 className="font-display text-2xl font-semibold">Moderation history</h2><p className="mt-1 text-sm text-muted-foreground">A durable audit of administrator actions.</p></div></div>{activity.isLoading ? <p className="p-6 text-sm text-muted-foreground">Loading activity…</p> : activity.data?.length ? <div className="divide-y">{activity.data.map(item => <div key={item.action.id} className="p-5"><p className="text-sm font-bold">{item.action.action.replace(/_/g, " ")}</p><p className="mt-1 text-xs text-muted-foreground">By {item.administrator.name || item.administrator.email || "administrator"} · {new Date(item.action.createdAt).toLocaleString()}</p>{item.action.reason ? <p className="mt-2 text-sm">{item.action.reason}</p> : null}</div>)}</div> : <p className="p-6 text-sm text-muted-foreground">No moderation actions have been recorded.</p>}</section>;
}
