import { ChevronLeft, ChevronRight, Plus, Trash2, X } from "lucide-react";
import { useEffect, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Dialog, DialogContent } from "@/components/ui/dialog";

export function StoryStrip() {
  const stories = trpc.stories.list.useQuery(); const overview = trpc.accounts.overview.useQuery(); const markViewed = trpc.stories.markViewed.useMutation({ onSuccess: () => stories.refetch() }); const removeStory = trpc.stories.remove.useMutation({ onSuccess: () => { stories.refetch(); setCurrent(null); } }); const [current, setCurrent] = useState<number | null>(null);
  const item = current === null ? null : stories.data?.[current];
  useEffect(() => { if (item && !item.viewedByViewer) markViewed.mutate({ storyId: item.id }); }, [item?.id]);
  if (!stories.isLoading && !stories.data?.length) return <section className="velora-surface flex items-center gap-4 p-4"><span className="grid h-11 w-11 place-items-center rounded-2xl border border-dashed border-primary/40 bg-primary/5 text-primary"><Plus className="h-5 w-5" /></span><div><p className="text-sm font-bold">Stories will appear here.</p><p className="text-xs text-muted-foreground">Share an image or video that fades after 24 hours.</p></div></section>;
  return <><section className="velora-surface overflow-x-auto p-3"><div className="flex min-w-max gap-4">{stories.data?.map((story, index) => <button key={story.id} onClick={() => setCurrent(index)} className="w-16 text-center"><span className={`block rounded-[1.15rem] p-0.5 ${story.viewedByViewer ? "bg-border" : "bg-[linear-gradient(135deg,#4258dd,#b748b7,#ef9266)]"}`}><span className="grid aspect-square place-items-center overflow-hidden rounded-[1rem] bg-secondary text-sm font-bold text-primary">{story.media.mimeType.startsWith("video/") ? <video src={story.media.url} className="h-full w-full object-cover" muted /> : <img src={story.media.url} alt={`${story.author.displayName}'s story`} className="h-full w-full object-cover" />}</span></span><span className="mt-1 block truncate text-[11px] font-semibold">{story.author.username}</span></button>)}</div></section><Dialog open={current !== null} onOpenChange={open => !open && setCurrent(null)}>{item ? <DialogContent className="h-[min(82vh,720px)] max-w-md overflow-hidden border-0 bg-zinc-950 p-0 text-white"><div className="absolute inset-x-5 top-4 z-10 h-1 overflow-hidden rounded-full bg-white/25"><div className="h-full w-full animate-pulse bg-white" /></div><div className="absolute right-3 top-6 z-10 flex gap-1">{overview.data?.activeAccountId === item.authorAccountId ? <button className="grid h-9 w-9 place-items-center rounded-full bg-black/35" onClick={() => removeStory.mutate({ storyId: item.id })} aria-label="Delete story"><Trash2 className="h-4 w-4" /></button> : null}<button className="grid h-9 w-9 place-items-center rounded-full bg-black/35" onClick={() => setCurrent(null)} aria-label="Close story"><X className="h-5 w-5" /></button></div><div className="h-full bg-black">{item.media.mimeType.startsWith("video/") ? <video src={item.media.url} className="h-full w-full object-contain" autoPlay controls /> : <img src={item.media.url} alt={item.caption || `${item.author.displayName}'s story`} className="h-full w-full object-contain" />}</div><div className="absolute inset-x-5 bottom-5 flex items-center justify-between"><button className="grid h-10 w-10 place-items-center rounded-full bg-black/35 disabled:opacity-30" onClick={() => setCurrent(index => index && index > 0 ? index - 1 : index)} disabled={!current} aria-label="Previous story"><ChevronLeft className="h-5 w-5" /></button><p className="max-w-[60%] truncate text-sm font-semibold">{item.author.displayName}{item.caption ? ` · ${item.caption}` : ""}</p><button className="grid h-10 w-10 place-items-center rounded-full bg-black/35 disabled:opacity-30" onClick={() => setCurrent(index => index !== null && stories.data && index < stories.data.length - 1 ? index + 1 : index)} disabled={!stories.data || current === stories.data.length - 1} aria-label="Next story"><ChevronRight className="h-5 w-5" /></button></div></DialogContent> : null}</Dialog></>;
}
